name: Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dtinth/setup-github-actions-caching-for-turbo@v1
      - uses: pnpm/action-setup@10693b3829bf86eb2572aef5f3571dcf5ca9287d # v2.2.2
      - name: Setup Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: pnpm
      - name: Install Dependencies
        run: pnpm install --prefer-offline
      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps
      - name: Build all packages
        run: pnpm exec turbo build
      - name: Run unit tests
        run: pnpm exec turbo test
      - name: Run Playwright tests
        run: pnpm exec playwright test
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
